const employees = [
  {
    id: '5d0c1260b28296a5da34dd5d',
    name: 'Sabrina',
    picture: 'http://placehold.it/32x32',
    age: 34,
    email: 'Sabrina@$pizzadaycare.com',
    phone: '+1 (902) 491-3777',
    address: '448 Provost Street, Morriston, Virgin Islands, 547',
    about: 'Lorem dolore cillum proident mollit sunt cupidatat mollit minim exercitation est ipsum ipsum labore fugiat. Anim tempor magna aliquip pariatur elit eiusmod do irure aliquip aute velit. Fugiat aliqua labore veniam consequat dolor elit non voluptate. Dolore consectetur cillum commodo nisi anim velit reprehenderit.',
  },
  {
    id: '5d0c1260cbfdb3ec02e3fd3e',
    name: 'Marjorie',
    picture: 'http://placehold.it/32x32',
    age: 28,
    email: 'Marjorie@$pizzadaycare.com',
    phone: '+1 (870) 465-2484',
    address: '601 Glenwood Road, Lowell, Oregon, 3340',
    about: 'Eiusmod do minim reprehenderit fugiat occaecat veniam quis ea dolore. Adipisicing sunt in reprehenderit sint. Anim veniam ad nulla incididunt duis enim in consectetur ipsum aute. Ullamco non sunt laboris nostrud sunt.',
  },
  {
    id: '5d0c126013b95e104667ae56',
    name: 'Madeleine',
    picture: 'http://placehold.it/32x32',
    age: 40,
    email: 'Madeleine@$pizzadaycare.com',
    phone: '+1 (889) 486-3165',
    address: '600 Bath Avenue, Whitmer, Mississippi, 6124',
    about: 'Enim incididunt elit excepteur nostrud pariatur reprehenderit cupidatat. Quis pariatur fugiat in eiusmod laboris magna consectetur nulla qui adipisicing laboris eiusmod. Do sunt dolore incididunt id anim id excepteur enim amet elit dolore minim tempor qui. Veniam et eu reprehenderit anim.',
  },
  {
    id: '5d0c126007d7dc4938ad4ea9',
    name: 'Shelby',
    picture: 'http://placehold.it/32x32',
    age: 28,
    email: 'Shelby@$pizzadaycare.com',
    phone: '+1 (875) 526-3185',
    address: '356 Ingraham Street, Magnolia, Delaware, 7653',
    about: 'Cillum nisi excepteur irure nisi laboris aliquip aute eu excepteur est irure veniam aliquip consequat. Ex cillum sit eiusmod laborum cupidatat nulla velit dolor commodo cillum eiusmod. Elit labore pariatur pariatur est laboris consequat dolor minim aliquip occaecat qui Lorem voluptate consequat. Incididunt consequat irure qui nulla mollit ipsum.',
  },
  {
    id: '5d0c12608ac5dc7df01dfa69',
    name: 'Sherrie',
    picture: 'http://placehold.it/32x32',
    age: 28,
    email: 'Sherrie@$pizzadaycare.com',
    phone: '+1 (977) 582-2198',
    address: '360 Gerald Court, Eggertsville, Colorado, 9276',
    about: 'Et voluptate enim nisi aliquip non exercitation. Cupidatat est sunt et culpa consectetur veniam cupidatat consequat aute ex nisi veniam consequat proident. Non esse fugiat ut Lorem magna sit pariatur laborum voluptate tempor. Proident duis aute pariatur adipisicing quis cillum officia est aute ex eu adipisicing. Exercitation aliquip eu enim eiusmod Lorem nulla duis nisi occaecat mollit. Labore exercitation cillum laborum ullamco excepteur minim dolor duis commodo Lorem eu magna laborum non.',
  },
  {
    id: '5d0c12603a35336defd97b1a',
    name: 'Jacqueline',
    picture: 'http://placehold.it/32x32',
    age: 26,
    email: 'Jacqueline@$pizzadaycare.com',
    phone: '+1 (924) 519-2889',
    address: '372 Gotham Avenue, Bend, Kentucky, 2664',
    about: 'Aute enim officia aliqua est incididunt sunt exercitation ex sunt qui anim id ad. Est enim culpa sit cillum officia ullamco irure commodo esse eu eiusmod irure deserunt ad. Commodo quis consectetur duis nostrud est labore qui ut labore adipisicing. Sunt fugiat consequat velit commodo ex do dolor do veniam velit pariatur consequat aute. Lorem voluptate ut labore quis duis sunt elit commodo aliqua. Minim occaecat irure fugiat occaecat consectetur duis culpa. Aliqua nostrud mollit enim officia quis.',
  },
  {
    id: '5d0c12604f694edc1d17e47a',
    name: 'Mcknight',
    picture: 'http://placehold.it/32x32',
    age: 36,
    email: 'Mcknight@$pizzadaycare.com',
    phone: '+1 (857) 509-2025',
    address: '789 Seabring Street, Shasta, Alaska, 5875',
    about: 'Excepteur aliqua occaecat dolor ad id aliquip incididunt irure eiusmod in esse irure. Laborum pariatur tempor ad ullamco magna occaecat ea labore ut eiusmod proident fugiat. Commodo consequat pariatur adipisicing aute consectetur duis minim duis adipisicing ipsum dolor sint ea commodo. Consectetur ipsum est aute irure sit mollit. Tempor sint ex fugiat cupidatat sunt.',
  },
  {
    id: '5d0c12604574a52c122a5762',
    name: 'Miles',
    picture: 'http://placehold.it/32x32',
    age: 20,
    email: 'Miles@$pizzadaycare.com',
    phone: '+1 (917) 518-3556',
    address: '448 Cleveland Street, Boling, Maine, 7334',
    about: 'Tempor officia duis dolor incididunt aute. Tempor adipisicing ullamco dolore nostrud velit. Consequat nisi deserunt reprehenderit aute adipisicing consectetur nisi.',
  },
];

export default employees;
